FROM liuchong/rustup:stable

RUN apt-get update
RUN apt-get install -y pkg-config libudev-dev librocksdb-dev libclang-dev clang

RUN curl -L https://github.com/solana-labs/solana/archive/refs/tags/v1.6.25.tar.gz --output src.tar.gz
RUN tar -xf src.tar.gz
RUN cd solana-1.6.25/
RUN ./scripts/cargo-install-all.sh .
RUN export PATH=$PWD/bin:$PATH
RUN solana-install init

ENV PATH="/root/.local/share/solana/install/active_release/bin:${PATH}"

